const DEFAULT_SAFE_INSET = 50;
const DEFAULT_DIRECTION = 'horizontal';
const DEFAULT_INDICATOR_SIZE = 40;
const DEFAULT_INDICATOR_COLOR = 'white';
const DEFAULT_CLOSE_BUTTON_TEXT = 'close';

export {
  DEFAULT_SAFE_INSET,
  DEFAULT_DIRECTION,
  DEFAULT_INDICATOR_SIZE,
  DEFAULT_INDICATOR_COLOR,
  DEFAULT_CLOSE_BUTTON_TEXT,
};
